import { Flex } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          justify={"center"}
          fontSize={"100px"}
          fontWeight="bold"
          fontStyle={"italic"}
        >
          ANAS BARRE
        </Flex>
      </main>
    </>
  );
}
